//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.Battle
{
public sealed partial class BuffConfig :  Bright.Config.BeanBase 
{
    public BuffConfig(ByteBuf _buf) 
    {
        BuffID = _buf.ReadInt();
        Desc = _buf.ReadString();
        BUFFtype = _buf.ReadInt();
        TimeType = _buf.ReadInt();
        Tctype = _buf.ReadInt();
        TargetType = _buf.ReadInt();
        TargetQuantity = _buf.ReadInt();
        ReplaceType = _buf.ReadInt();
        PrefId = _buf.ReadInt();
        BUFFicon = _buf.ReadInt();
        Trigger = _buf.ReadInt();
        Attack = _buf.ReadInt();
        Defense = _buf.ReadInt();
        Life = _buf.ReadInt();
        Speed = _buf.ReadInt();
        Anger = _buf.ReadInt();
        Db = _buf.ReadInt();
        Wound = _buf.ReadInt();
        Pj = _buf.ReadInt();
        Pjdikang = _buf.ReadInt();
        Crit = _buf.ReadInt();
        CriticalImpact = _buf.ReadInt();
        Block = _buf.ReadInt();
        Accurate = _buf.ReadInt();
        Baojidikang = _buf.ReadInt();
        Baoshangdikang = _buf.ReadInt();
        Xixue = _buf.ReadInt();
        Jnshzj = _buf.ReadInt();
        Jnshjs = _buf.ReadInt();
        Kzmz = _buf.ReadInt();
        Miankong = _buf.ReadInt();
        Jnglzj = _buf.ReadInt();
        Jngljs = _buf.ReadInt();
        PostInit();
    }

    public static BuffConfig DeserializeBuffConfig(ByteBuf _buf)
    {
        return new Battle.BuffConfig(_buf);
    }

    /// <summary>
    /// BuffID
    /// </summary>
    public int BuffID { get; private set; }
    /// <summary>
    /// 描述
    /// </summary>
    public string Desc { get; private set; }
    /// <summary>
    /// BUFF类型
    /// </summary>
    public int BUFFtype { get; private set; }
    /// <summary>
    /// 持续回合类型
    /// </summary>
    public int TimeType { get; private set; }
    /// <summary>
    /// 触发条件类型
    /// </summary>
    public int Tctype { get; private set; }
    /// <summary>
    /// 作用目标类型
    /// </summary>
    public int TargetType { get; private set; }
    /// <summary>
    /// 目标数量
    /// </summary>
    public int TargetQuantity { get; private set; }
    /// <summary>
    /// 叠加类型
    /// </summary>
    public int ReplaceType { get; private set; }
    /// <summary>
    /// BUFF特效
    /// </summary>
    public int PrefId { get; private set; }
    /// <summary>
    /// BUFF图标
    /// </summary>
    public int BUFFicon { get; private set; }
    /// <summary>
    /// 触发概率（万分比）
    /// </summary>
    public int Trigger { get; private set; }
    /// <summary>
    /// 攻击（万分比）
    /// </summary>
    public int Attack { get; private set; }
    /// <summary>
    /// 防御<br/>（万分比）
    /// </summary>
    public int Defense { get; private set; }
    /// <summary>
    /// 生命<br/>（万分比）
    /// </summary>
    public int Life { get; private set; }
    /// <summary>
    /// 速度<br/>（万分比）
    /// </summary>
    public int Speed { get; private set; }
    /// <summary>
    /// 怒气<br/>（数值）
    /// </summary>
    public int Anger { get; private set; }
    /// <summary>
    /// 增伤<br/>（万分比）
    /// </summary>
    public int Db { get; private set; }
    /// <summary>
    /// 减伤<br/>（万分比）
    /// </summary>
    public int Wound { get; private set; }
    /// <summary>
    /// 破甲<br/>（万分比）
    /// </summary>
    public int Pj { get; private set; }
    /// <summary>
    /// 破甲抵抗<br/>（万分比）
    /// </summary>
    public int Pjdikang { get; private set; }
    /// <summary>
    /// 暴击<br/>（万分比）
    /// </summary>
    public int Crit { get; private set; }
    /// <summary>
    /// 暴击效果<br/>（万分比）
    /// </summary>
    public int CriticalImpact { get; private set; }
    /// <summary>
    /// 格挡<br/>（万分比）
    /// </summary>
    public int Block { get; private set; }
    /// <summary>
    /// 精准<br/>（万分比）
    /// </summary>
    public int Accurate { get; private set; }
    /// <summary>
    /// 暴击抵抗<br/>（万分比）
    /// </summary>
    public int Baojidikang { get; private set; }
    /// <summary>
    /// 爆伤抵抗<br/>（万分比）
    /// </summary>
    public int Baoshangdikang { get; private set; }
    /// <summary>
    /// 吸血<br/>（万分比）
    /// </summary>
    public int Xixue { get; private set; }
    /// <summary>
    /// 技能伤害增加<br/>（万分比）
    /// </summary>
    public int Jnshzj { get; private set; }
    /// <summary>
    /// 技能伤害减少<br/>（万分比）
    /// </summary>
    public int Jnshjs { get; private set; }
    /// <summary>
    /// 控制命中<br/>（万分比
    /// </summary>
    public int Kzmz { get; private set; }
    /// <summary>
    /// 免控<br/>（万分比）
    /// </summary>
    public int Miankong { get; private set; }
    /// <summary>
    /// 技能概率增加<br/>（万分比）
    /// </summary>
    public int Jnglzj { get; private set; }
    /// <summary>
    /// 技能概率减少<br/>（万分比
    /// </summary>
    public int Jngljs { get; private set; }

    public const int __ID__ = 1807662187;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "BuffID:" + BuffID + ","
        + "Desc:" + Desc + ","
        + "BUFFtype:" + BUFFtype + ","
        + "TimeType:" + TimeType + ","
        + "Tctype:" + Tctype + ","
        + "TargetType:" + TargetType + ","
        + "TargetQuantity:" + TargetQuantity + ","
        + "ReplaceType:" + ReplaceType + ","
        + "PrefId:" + PrefId + ","
        + "BUFFicon:" + BUFFicon + ","
        + "Trigger:" + Trigger + ","
        + "Attack:" + Attack + ","
        + "Defense:" + Defense + ","
        + "Life:" + Life + ","
        + "Speed:" + Speed + ","
        + "Anger:" + Anger + ","
        + "Db:" + Db + ","
        + "Wound:" + Wound + ","
        + "Pj:" + Pj + ","
        + "Pjdikang:" + Pjdikang + ","
        + "Crit:" + Crit + ","
        + "CriticalImpact:" + CriticalImpact + ","
        + "Block:" + Block + ","
        + "Accurate:" + Accurate + ","
        + "Baojidikang:" + Baojidikang + ","
        + "Baoshangdikang:" + Baoshangdikang + ","
        + "Xixue:" + Xixue + ","
        + "Jnshzj:" + Jnshzj + ","
        + "Jnshjs:" + Jnshjs + ","
        + "Kzmz:" + Kzmz + ","
        + "Miankong:" + Miankong + ","
        + "Jnglzj:" + Jnglzj + ","
        + "Jngljs:" + Jngljs + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}