
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.EntityConfig
{
public sealed partial class EntityBaseInfoConfig : Luban.BeanBase
{
    public EntityBaseInfoConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        ResPath = _buf.ReadString();
        Icon = _buf.ReadString();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
    }

    public static EntityBaseInfoConfig DeserializeEntityBaseInfoConfig(ByteBuf _buf)
    {
        return new EntityConfig.EntityBaseInfoConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 资源路径
    /// </summary>
    public readonly string ResPath;
    /// <summary>
    /// 图标
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
   
    public const int __ID__ = 745540429;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "resPath:" + ResPath + ","
        + "icon:" + Icon + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "}";
    }
}

}

