
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.EntityConfig
{
public partial class EntityActorInfo
{
    private readonly System.Collections.Generic.Dictionary<int, EntityConfig.EntityActorInfoConfig> _dataMap;
    private readonly System.Collections.Generic.List<EntityConfig.EntityActorInfoConfig> _dataList;
    
    public EntityActorInfo(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, EntityConfig.EntityActorInfoConfig>();
        _dataList = new System.Collections.Generic.List<EntityConfig.EntityActorInfoConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            EntityConfig.EntityActorInfoConfig _v;
            _v = EntityConfig.EntityActorInfoConfig.DeserializeEntityActorInfoConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, EntityConfig.EntityActorInfoConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<EntityConfig.EntityActorInfoConfig> DataList => _dataList;

    public EntityConfig.EntityActorInfoConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public EntityConfig.EntityActorInfoConfig Get(int key) => _dataMap[key];
    public EntityConfig.EntityActorInfoConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

