
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Threading.Tasks;

namespace cfg
{
public partial class Tables
{
    public Common.Config Config {get; private set; }
    public EntityConfig.EntityBaseInfo EntityBaseInfo {get; private set; }
    public EntityConfig.EntityActorInfo EntityActorInfo {get; private set; }
    public L10N.Localize_CN LocalizeCN {get; private set; }
    public L10N.Localize_EN LocalizeEN {get; private set; }
    public L10N.Localize_TW LocalizeTW {get; private set; }
    public Music.TbMusicItem TbMusicItem {get; private set; }

    public Tables() {}

    public Tables(System.Func<string, ByteBuf> loader)
    {
        Config = new Common.Config(loader("common_config"));
        EntityBaseInfo = new EntityConfig.EntityBaseInfo(loader("entityconfig_entitybaseinfo"));
        EntityActorInfo = new EntityConfig.EntityActorInfo(loader("entityconfig_entityactorinfo"));
        LocalizeCN = new L10N.Localize_CN(loader("l10n_localize_cn"));
        LocalizeEN = new L10N.Localize_EN(loader("l10n_localize_en"));
        LocalizeTW = new L10N.Localize_TW(loader("l10n_localize_tw"));
        TbMusicItem = new Music.TbMusicItem(loader("music_tbmusicitem"));
        ResolveRef();
    }

    public async Task LoadAsync(System.Func<string, Task<ByteBuf>> loader)
    {
        Config = new Common.Config(await loader("common_config")); 
        EntityBaseInfo = new EntityConfig.EntityBaseInfo(await loader("entityconfig_entitybaseinfo")); 
        EntityActorInfo = new EntityConfig.EntityActorInfo(await loader("entityconfig_entityactorinfo")); 
        LocalizeCN = new L10N.Localize_CN(await loader("l10n_localize_cn")); 
        LocalizeEN = new L10N.Localize_EN(await loader("l10n_localize_en")); 
        LocalizeTW = new L10N.Localize_TW(await loader("l10n_localize_tw")); 
        TbMusicItem = new Music.TbMusicItem(await loader("music_tbmusicitem")); 
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        Config.ResolveRef(this);
        EntityBaseInfo.ResolveRef(this);
        EntityActorInfo.ResolveRef(this);
        LocalizeCN.ResolveRef(this);
        LocalizeEN.ResolveRef(this);
        LocalizeTW.ResolveRef(this);
        TbMusicItem.ResolveRef(this);
    }

    //================Start L10N==================
    public async Task SwitchToLocalizeCN(System.Func<string, Task<ByteBuf>> loader,System.Func<string, string, string> translator)
    {
        LocalizeCN??=new L10N.Localize_CN(await loader("l10n_localize_cn"));
    }
    public async Task SwitchToLocalizeEN(System.Func<string, Task<ByteBuf>> loader,System.Func<string, string, string> translator)
    {
        LocalizeEN??=new L10N.Localize_EN(await loader("l10n_localize_en"));
    }
    public async Task SwitchToLocalizeTW(System.Func<string, Task<ByteBuf>> loader,System.Func<string, string, string> translator)
    {
        LocalizeTW??=new L10N.Localize_TW(await loader("l10n_localize_tw"));
    }
    //================End L10N==================
}

}
