
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Common
{
public sealed partial class GameConfig : Luban.BeanBase
{
    public GameConfig(ByteBuf _buf) 
    {
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);EntranceName = new string[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { string __e0;__e0 = _buf.ReadString(); EntranceName[__index0] = __e0;}}
        DefaultActorId = _buf.ReadInt();
    }

    public static GameConfig DeserializeGameConfig(ByteBuf _buf)
    {
        return new Common.GameConfig(_buf);
    }

    /// <summary>
    /// 入口多语言文本
    /// </summary>
    public readonly string[] EntranceName;
    /// <summary>
    /// 默认角色实体id
    /// </summary>
    public readonly int DefaultActorId;
   
    public const int __ID__ = 1400028599;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "entranceName:" + Luban.StringUtil.CollectionToString(EntranceName) + ","
        + "defaultActorId:" + DefaultActorId + ","
        + "}";
    }
}

}

