
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.L10N
{
public partial class Localize_TW
{
    private readonly System.Collections.Generic.Dictionary<string, L10N.LocalizeConfig_TW> _dataMap;
    private readonly System.Collections.Generic.List<L10N.LocalizeConfig_TW> _dataList;
    
    public Localize_TW(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, L10N.LocalizeConfig_TW>();
        _dataList = new System.Collections.Generic.List<L10N.LocalizeConfig_TW>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            L10N.LocalizeConfig_TW _v;
            _v = L10N.LocalizeConfig_TW.DeserializeLocalizeConfig_TW(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, L10N.LocalizeConfig_TW> DataMap => _dataMap;
    public System.Collections.Generic.List<L10N.LocalizeConfig_TW> DataList => _dataList;

    public L10N.LocalizeConfig_TW GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public L10N.LocalizeConfig_TW Get(string key) => _dataMap[key];
    public L10N.LocalizeConfig_TW this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

