
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.L10N
{
public sealed partial class LocalizeConfig_CN : L10N.LocalizeConfig
{
    public LocalizeConfig_CN(ByteBuf _buf)  : base(_buf) 
    {
        TextCn = _buf.ReadString();
    }

    public static LocalizeConfig_CN DeserializeLocalizeConfig_CN(ByteBuf _buf)
    {
        return new L10N.LocalizeConfig_CN(_buf);
    }

    public readonly string TextCn;
   
    public const int __ID__ = 1033709428;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "key:" + Key + ","
        + "textCn:" + TextCn + ","
        + "}";
    }
}

}

