
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Common
{
public partial class Config
{

     private readonly Common.GameConfig _data;

     public Common.GameConfig Data => _data;

    public Config(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = Common.GameConfig.DeserializeGameConfig(_buf);
    }


    /// <summary>
    /// 默认角色实体id
    /// </summary>
     public int DefaultActorId => _data.DefaultActorId;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }
}

}

