
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Common
{
public sealed partial class GameConfig : Luban.BeanBase
{
    public GameConfig(ByteBuf _buf) 
    {
        DefaultActorId = _buf.ReadInt();
    }

    public static GameConfig DeserializeGameConfig(ByteBuf _buf)
    {
        return new Common.GameConfig(_buf);
    }

    /// <summary>
    /// 默认角色实体id
    /// </summary>
    public readonly int DefaultActorId;
   
    public const int __ID__ = 1400028599;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "defaultActorId:" + DefaultActorId + ","
        + "}";
    }
}

}

