//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.basecorpslevelexp
{
public sealed partial class basecorpslevelexp :  Bright.Config.BeanBase 
{
    public basecorpslevelexp(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Level = _buf.ReadInt();
        Type = _buf.ReadInt();
        Exp = _buf.ReadInt();
        Param1 = _buf.ReadInt();
        Param2 = _buf.ReadInt();
        Param3 = _buf.ReadInt();
        AddLife = _buf.ReadInt();
        AddAtk = _buf.ReadInt();
        AddDef = _buf.ReadInt();
        AddSpeed = _buf.ReadInt();
        PostInit();
    }

    public static basecorpslevelexp Deserializebasecorpslevelexp(ByteBuf _buf)
    {
        return new basecorpslevelexp.basecorpslevelexp(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 等级
    /// </summary>
    public int Level { get; private set; }
    /// <summary>
    /// 类型
    /// </summary>
    public int Type { get; private set; }
    /// <summary>
    /// 升级金币数值 
    /// </summary>
    public int Exp { get; private set; }
    /// <summary>
    /// 英雄ID
    /// </summary>
    public int Param1 { get; private set; }
    /// <summary>
    /// 升级增加ID
    /// </summary>
    public int Param2 { get; private set; }
    /// <summary>
    /// 突破ID
    /// </summary>
    public int Param3 { get; private set; }
    /// <summary>
    /// 增加生命（万分比）
    /// </summary>
    public int AddLife { get; private set; }
    /// <summary>
    /// 增加攻击（万分比）
    /// </summary>
    public int AddAtk { get; private set; }
    /// <summary>
    /// 增加防御（万分比）
    /// </summary>
    public int AddDef { get; private set; }
    /// <summary>
    /// 增加速度（万分比）
    /// </summary>
    public int AddSpeed { get; private set; }

    public const int __ID__ = 1382779700;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Level:" + Level + ","
        + "Type:" + Type + ","
        + "Exp:" + Exp + ","
        + "Param1:" + Param1 + ","
        + "Param2:" + Param2 + ","
        + "Param3:" + Param3 + ","
        + "AddLife:" + AddLife + ","
        + "AddAtk:" + AddAtk + ","
        + "AddDef:" + AddDef + ","
        + "AddSpeed:" + AddSpeed + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}