//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.basecorpslevelexp
{
   
public partial class TbCoprsLevelExp
{
    private readonly Dictionary<int, basecorpslevelexp.basecorpslevelexp> _dataMap;
    private readonly List<basecorpslevelexp.basecorpslevelexp> _dataList;
    
    public TbCoprsLevelExp(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, basecorpslevelexp.basecorpslevelexp>();
        _dataList = new List<basecorpslevelexp.basecorpslevelexp>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            basecorpslevelexp.basecorpslevelexp _v;
            _v = basecorpslevelexp.basecorpslevelexp.Deserializebasecorpslevelexp(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, basecorpslevelexp.basecorpslevelexp> DataMap => _dataMap;
    public List<basecorpslevelexp.basecorpslevelexp> DataList => _dataList;

    public basecorpslevelexp.basecorpslevelexp GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public basecorpslevelexp.basecorpslevelexp Get(int key) => _dataMap[key];
    public basecorpslevelexp.basecorpslevelexp this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}