// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Pb {

  /// <summary>Holder for reflection information generated from Enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for Enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpFbnVtLnByb3RvEgJwYiojCglUZXN0RW51bTESCgoGVEVTVF8wEAASCgoG",
            "VEVTVF8xEAEqIwoJVGVzdEVudW0yEgoKBlRFU1RfMxAAEgoKBlRFU1RfNBAE",
            "QgxaBS4vO3BiqgICUGJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Pb.TestEnum1), typeof(global::Pb.TestEnum2), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum TestEnum1 {
    [pbr::OriginalName("TEST_0")] Test0 = 0,
    [pbr::OriginalName("TEST_1")] Test1 = 1,
  }

  public enum TestEnum2 {
    [pbr::OriginalName("TEST_3")] Test3 = 0,
    [pbr::OriginalName("TEST_4")] Test4 = 4,
  }

  #endregion

}

#endregion Designer generated code
