
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.L10N
{
public sealed partial class LocalizeConfig_TW : L10N.LocalizeConfig
{
    public LocalizeConfig_TW(ByteBuf _buf)  : base(_buf) 
    {
        TextTw = _buf.ReadString();
    }

    public static LocalizeConfig_TW DeserializeLocalizeConfig_TW(ByteBuf _buf)
    {
        return new L10N.LocalizeConfig_TW(_buf);
    }

    public readonly string TextTw;
   
    public const int __ID__ = 1033709964;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "key:" + Key + ","
        + "textTw:" + TextTw + ","
        + "}";
    }
}

}

