
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.L10N
{
public sealed partial class LocalizeConfig_EN : L10N.LocalizeConfig
{
    public LocalizeConfig_EN(ByteBuf _buf)  : base(_buf) 
    {
        TextEn = _buf.ReadString();
    }

    public static LocalizeConfig_EN DeserializeLocalizeConfig_EN(ByteBuf _buf)
    {
        return new L10N.LocalizeConfig_EN(_buf);
    }

    public readonly string TextEn;
   
    public const int __ID__ = 1033709490;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "key:" + Key + ","
        + "textEn:" + TextEn + ","
        + "}";
    }
}

}

