
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.L10N
{
public abstract partial class LocalizeConfig : Luban.BeanBase
{
    public LocalizeConfig(ByteBuf _buf) 
    {
        Key = _buf.ReadString();
    }

    public static LocalizeConfig DeserializeLocalizeConfig(ByteBuf _buf)
    {
        switch (_buf.ReadInt())
        {
            case L10N.LocalizeConfig_CN.__ID__: return new L10N.LocalizeConfig_CN(_buf);
            case L10N.LocalizeConfig_EN.__ID__: return new L10N.LocalizeConfig_EN(_buf);
            case L10N.LocalizeConfig_TW.__ID__: return new L10N.LocalizeConfig_TW(_buf);
            default: throw new SerializationException();
        }
    }

    public readonly string Key;
   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "key:" + Key + ","
        + "}";
    }
}

}

