
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Music
{
public sealed partial class MusicItem : Luban.BeanBase
{
    public MusicItem(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Artist = _buf.ReadString();
        Desc = _buf.ReadString();
        Icon = _buf.ReadString();
        ConfigPath = _buf.ReadString();
        ResPath = _buf.ReadString();
        Bpm = _buf.ReadInt();
        Length = _buf.ReadInt();
        ReadyTime = _buf.ReadFloat();
        VjRes = _buf.ReadString();
        VjStartTime = _buf.ReadFloat();
    }

    public static MusicItem DeserializeMusicItem(ByteBuf _buf)
    {
        return new Music.MusicItem(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 歌曲名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 歌手
    /// </summary>
    public readonly string Artist;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 图标名称
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 音乐配置路径
    /// </summary>
    public readonly string ConfigPath;
    /// <summary>
    /// 音乐资源路径
    /// </summary>
    public readonly string ResPath;
    /// <summary>
    /// BPM
    /// </summary>
    public readonly int Bpm;
    /// <summary>
    /// 时长(s)
    /// </summary>
    public readonly int Length;
    /// <summary>
    /// 预备时长
    /// </summary>
    public readonly float ReadyTime;
    /// <summary>
    /// VJ资源路径
    /// </summary>
    public readonly string VjRes;
    /// <summary>
    /// VJ开始播放的时间
    /// </summary>
    public readonly float VjStartTime;
   
    public const int __ID__ = -1771654641;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "artist:" + Artist + ","
        + "desc:" + Desc + ","
        + "icon:" + Icon + ","
        + "configPath:" + ConfigPath + ","
        + "resPath:" + ResPath + ","
        + "bpm:" + Bpm + ","
        + "length:" + Length + ","
        + "readyTime:" + ReadyTime + ","
        + "vjRes:" + VjRes + ","
        + "vjStartTime:" + VjStartTime + ","
        + "}";
    }
}

}

