
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Music
{
public partial class TbMusicItem
{
    private readonly System.Collections.Generic.Dictionary<int, Music.MusicItem> _dataMap;
    private readonly System.Collections.Generic.List<Music.MusicItem> _dataList;
    
    public TbMusicItem(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Music.MusicItem>();
        _dataList = new System.Collections.Generic.List<Music.MusicItem>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Music.MusicItem _v;
            _v = Music.MusicItem.DeserializeMusicItem(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Music.MusicItem> DataMap => _dataMap;
    public System.Collections.Generic.List<Music.MusicItem> DataList => _dataList;

    public Music.MusicItem GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Music.MusicItem Get(int key) => _dataMap[key];
    public Music.MusicItem this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

