//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.basecorpsstar
{
public sealed partial class basecorpsstar :  Bright.Config.BeanBase 
{
    public basecorpsstar(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Star = _buf.ReadInt();
        CorpsId = _buf.ReadInt();
        StarGrade = _buf.ReadInt();
        ChipCost = _buf.ReadInt();
        AddLife = _buf.ReadInt();
        AddAtk = _buf.ReadInt();
        AddDef = _buf.ReadInt();
        AddSpeed = _buf.ReadInt();
        Anger = _buf.ReadInt();
        DamageIncrease = _buf.ReadInt();
        DamageReduce = _buf.ReadInt();
        BreakArmor = _buf.ReadInt();
        BreakArmorResistance = _buf.ReadInt();
        Crit = _buf.ReadInt();
        CritEffect = _buf.ReadInt();
        Parry = _buf.ReadInt();
        Accurate = _buf.ReadInt();
        CritResistance = _buf.ReadInt();
        CritDamageResistance = _buf.ReadInt();
        SkillDamageIncrease = _buf.ReadInt();
        ControlAccurate = _buf.ReadInt();
        ControlResistance = _buf.ReadInt();
        PostInit();
    }

    public static basecorpsstar Deserializebasecorpsstar(ByteBuf _buf)
    {
        return new basecorpsstar.basecorpsstar(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 星级
    /// </summary>
    public int Star { get; private set; }
    /// <summary>
    /// 英雄ID
    /// </summary>
    public int CorpsId { get; private set; }
    /// <summary>
    /// 星级品阶
    /// </summary>
    public int StarGrade { get; private set; }
    /// <summary>
    /// 升星碎片数量
    /// </summary>
    public int ChipCost { get; private set; }
    /// <summary>
    /// 增加生命（万分比）
    /// </summary>
    public int AddLife { get; private set; }
    /// <summary>
    /// 增加攻击（万分比）
    /// </summary>
    public int AddAtk { get; private set; }
    /// <summary>
    /// 增加防御（万分比）
    /// </summary>
    public int AddDef { get; private set; }
    /// <summary>
    /// 增加速度（万分比）
    /// </summary>
    public int AddSpeed { get; private set; }
    /// <summary>
    /// 怒气
    /// </summary>
    public int Anger { get; private set; }
    /// <summary>
    /// 增伤
    /// </summary>
    public int DamageIncrease { get; private set; }
    /// <summary>
    /// 减伤
    /// </summary>
    public int DamageReduce { get; private set; }
    /// <summary>
    /// 破甲
    /// </summary>
    public int BreakArmor { get; private set; }
    /// <summary>
    /// 破甲抵抗
    /// </summary>
    public int BreakArmorResistance { get; private set; }
    /// <summary>
    /// 暴击
    /// </summary>
    public int Crit { get; private set; }
    /// <summary>
    /// 暴击效果
    /// </summary>
    public int CritEffect { get; private set; }
    /// <summary>
    /// 格挡
    /// </summary>
    public int Parry { get; private set; }
    /// <summary>
    /// 精准
    /// </summary>
    public int Accurate { get; private set; }
    /// <summary>
    /// 暴击抵抗
    /// </summary>
    public int CritResistance { get; private set; }
    /// <summary>
    /// 爆伤抵抗
    /// </summary>
    public int CritDamageResistance { get; private set; }
    /// <summary>
    /// 技能伤害增加
    /// </summary>
    public int SkillDamageIncrease { get; private set; }
    /// <summary>
    /// 控制命中
    /// </summary>
    public int ControlAccurate { get; private set; }
    /// <summary>
    /// 免控<br/>
    /// </summary>
    public int ControlResistance { get; private set; }

    public const int __ID__ = -333639322;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Star:" + Star + ","
        + "CorpsId:" + CorpsId + ","
        + "StarGrade:" + StarGrade + ","
        + "ChipCost:" + ChipCost + ","
        + "AddLife:" + AddLife + ","
        + "AddAtk:" + AddAtk + ","
        + "AddDef:" + AddDef + ","
        + "AddSpeed:" + AddSpeed + ","
        + "Anger:" + Anger + ","
        + "DamageIncrease:" + DamageIncrease + ","
        + "DamageReduce:" + DamageReduce + ","
        + "BreakArmor:" + BreakArmor + ","
        + "BreakArmorResistance:" + BreakArmorResistance + ","
        + "Crit:" + Crit + ","
        + "CritEffect:" + CritEffect + ","
        + "Parry:" + Parry + ","
        + "Accurate:" + Accurate + ","
        + "CritResistance:" + CritResistance + ","
        + "CritDamageResistance:" + CritDamageResistance + ","
        + "SkillDamageIncrease:" + SkillDamageIncrease + ","
        + "ControlAccurate:" + ControlAccurate + ","
        + "ControlResistance:" + ControlResistance + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}