//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.basecorpsstar
{
   
public partial class TbCoprsStar
{
    private readonly Dictionary<int, basecorpsstar.basecorpsstar> _dataMap;
    private readonly List<basecorpsstar.basecorpsstar> _dataList;
    
    public TbCoprsStar(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, basecorpsstar.basecorpsstar>();
        _dataList = new List<basecorpsstar.basecorpsstar>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            basecorpsstar.basecorpsstar _v;
            _v = basecorpsstar.basecorpsstar.Deserializebasecorpsstar(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, basecorpsstar.basecorpsstar> DataMap => _dataMap;
    public List<basecorpsstar.basecorpsstar> DataList => _dataList;

    public basecorpsstar.basecorpsstar GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public basecorpsstar.basecorpsstar Get(int key) => _dataMap[key];
    public basecorpsstar.basecorpsstar this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}