//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.basecorpsadvance
{
public sealed partial class basecorpsadvance :  Bright.Config.BeanBase 
{
    public basecorpsadvance(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Level = _buf.ReadInt();
        Exp = _buf.ReadInt();
        AddLife = _buf.ReadInt();
        AddAtk = _buf.ReadInt();
        AddDef = _buf.ReadInt();
        AddSpeed = _buf.ReadInt();
        PostInit();
    }

    public static basecorpsadvance Deserializebasecorpsadvance(ByteBuf _buf)
    {
        return new basecorpsadvance.basecorpsadvance(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 需要等级
    /// </summary>
    public int Level { get; private set; }
    /// <summary>
    /// 突破消耗道具数量
    /// </summary>
    public int Exp { get; private set; }
    /// <summary>
    /// 增加生命（万分比）
    /// </summary>
    public int AddLife { get; private set; }
    /// <summary>
    /// 增加攻击（万分比）
    /// </summary>
    public int AddAtk { get; private set; }
    /// <summary>
    /// 增加防御（万分比）
    /// </summary>
    public int AddDef { get; private set; }
    /// <summary>
    /// 增加速度（万分比）
    /// </summary>
    public int AddSpeed { get; private set; }

    public const int __ID__ = 1938648430;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Level:" + Level + ","
        + "Exp:" + Exp + ","
        + "AddLife:" + AddLife + ","
        + "AddAtk:" + AddAtk + ","
        + "AddDef:" + AddDef + ","
        + "AddSpeed:" + AddSpeed + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}