//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace GameConfig.basecorpsadvance
{
   
public partial class TbCoprsAdvance
{
    private readonly Dictionary<int, basecorpsadvance.basecorpsadvance> _dataMap;
    private readonly List<basecorpsadvance.basecorpsadvance> _dataList;
    
    public TbCoprsAdvance(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, basecorpsadvance.basecorpsadvance>();
        _dataList = new List<basecorpsadvance.basecorpsadvance>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            basecorpsadvance.basecorpsadvance _v;
            _v = basecorpsadvance.basecorpsadvance.Deserializebasecorpsadvance(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, basecorpsadvance.basecorpsadvance> DataMap => _dataMap;
    public List<basecorpsadvance.basecorpsadvance> DataList => _dataList;

    public basecorpsadvance.basecorpsadvance GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public basecorpsadvance.basecorpsadvance Get(int key) => _dataMap[key];
    public basecorpsadvance.basecorpsadvance this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}